<a href="https://colab.research.google.com/github/ProfLunaLuis/Algebra-Lineal/blob/main/seidel_ej2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import numpy.linalg as al
from sympy import *
from scipy import linalg

A = np.array([[10, 2, -1],
              [-3, -6, 2],
              [1, 1, 5]])
b = np.array([27, -61.5, -21.5])
print(linalg.solve(A, b))

#Declaramos C.I.
xa0=np.array([0,0,0])
xa_1=xa0[0]
xa_2=xa0[1]
xa_3=xa0[2]
# Genero matriz donde se guardan datos
A = np.zeros((10,3))
#
for i in range(1, 10, 1):
 xn_1=(27-2*xa_2+xa_3)/10
 xn_2=(-61.5+3*xa_1-2*xa_3)/-6
 xn_3=(-21.5-xa_1-xa_2)/5
# Guardo los datos de x1, x2, x3 y x4 en el vector xa
 xa=np.array([xn_1,xn_2,xn_3])
 #norma_inf=al.norm(xa-xa0,np.inf)/al.norm(xa,np.inf)
# print(norma_inf)
# En la fila i se guardan los datos de x1, x2, x3 y x4
 A[i]=xa
 norma_inf=al.norm(A[i]-A[i-1],np.inf)/al.norm(A[i],np.inf)
 print(norma_inf)
 if norma_inf<0.001:
    break
#Accedo a los datos del vector para que se usen en el siguiente ciclo
 xa_1=xa[0]
 xa_2=xa[1]
 xa_3=xa[2]
#
print(A)

[ 0.5  8.  -6. ]
1.0
0.37276785714285726
0.13421164470888244
0.025114454794671826
0.0075039098807277655
0.002846585392467295
0.0004894053982486586
[[ 0.          0.          0.        ]
 [ 2.7        10.25       -4.3       ]
 [ 0.22        7.46666667 -6.89      ]
 [ 0.51766667  7.84333333 -5.83733333]
 [ 0.5476      8.04538889 -5.9722    ]
 [ 0.49370222  7.98546667 -6.01859778]
 [ 0.50104689  7.99694963 -5.99583378]
 [ 0.5010267   8.0008653  -5.9995993 ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
